[package]
name = "mocked-runtime"
version = "1.0.1"
authors = [""]
edition = "2021"
license = "Apache-2.0"
homepage = ""
repository = ""
description = "Mokcked Runtime for Testing"

[dependencies]
avail-core = { git = "https://github.com/availproject/avail-core", tag = "node-v1.8.0.0", default-features = false, features = ["runtime"] }
kate = { git = "https://github.com/availproject/avail-core", tag = "node-v1.8.0.0", default-features = false }
da-control = { path = "../dactr" }

scale-info = { version = "2.5.0", features = ["derive"] }
codec = { package = "parity-scale-codec", version = "3", features = ["derive"] }
parity-util-mem = { version = "0.12.0", features = ["primitive-types"] }
derive_more = "0.99.17" 
serde = { version = "1.0.121", features = ["derive"] }

frame-support = "4.0.0-dev"
sp-runtime = "24.0.0"
sp-core = "21.0.0"
sp-staking = "4.0.0-dev"
sp-io = "23.0.0"
sp-version = "22.0.0"
sp-inherents = "4.0.0-dev"
sp-std = "8.0.0"

# Pallets
frame-system = { path = "../system" }
pallet-transaction-payment = "4.0.0-dev"
pallet-balances = "4.0.0-dev"
pallet-timestamp = "4.0.0-dev"
pallet-babe = "4.0.0-dev"
pallet-staking = "4.0.0-dev"



[features]
default = ["std"]
std = [ ]
try-runtime = []
